version: '3.5'
services:

  bitcoind:
    container_name: bitcoind
    image: bitcoind:${BITCOIND_VERSION}
    build: 
      context: src/bitcoind
      args: 
        TARGETPLATFORM: ${TARGETPLATFORM}
    restart: always
    stop_grace_period: 5m
    ports:
      - 8333:8333
    expose:
      - 8332
      - 28332
      - 28333
    networks:
      - bitcoind
      - tor
    volumes:
      - ../data/bitcoind/:/home/bitcoin/.bitcoin:rw # data
      - ./dynamic_config/bitcoind.conf:/home/bitcoin/.bitcoin/bitcoin.conf:rw # config, rw to chown

  lnd:
    container_name: lnd
    image: lnd:${LND_VERSION}
    build:
      context: src/lnd
      args:
        checkout: v0.15.0-beta
    restart: always
    stop_grace_period: 1m
    depends_on:
      - bitcoind
    ports:
      - 9735:9735
    expose:
      - 10009
    networks:
      - bitcoind
      - lnd
      - tor
    depends_on:
      - bitcoind
    volumes:
      - ../data/lnd/:/root/.lnd:rw
      - ./dynamic_config/lnd.conf:/root/.lnd/lnd.conf:ro

  lndhub:
    container_name: lndhub
    image: lndhub:${LNDHUB_VERSION}
    build: src/lndhub
    restart: always
    stop_grace_period: 30s
    env_file: dynamic_config/lndhub.env
    networks:
      - lnd
      - lndhub
      - nginx
    depends_on:
      - lnd
      - lndhub-redis
      - nginx
    volumes:
      - ../data/lnd:/lnd:ro

  lndhub-redis:
    container_name: lndhub-redis
    image: redis:${REDIS_VERSION}
    build: src/redis
    restart: always
    stop_grace_period: 30s
    command: redis-server --appendonly yes --appendfsync always
    expose:
      - 6379
    networks:
      - lndhub
    volumes:
      - ../data/lndhub-redis/:/data:rw

  lndhub-tg:
    container_name: lndhub-tg
    image: lndhub-tg:${LNDHUB_TG_VERSION}
    build: src/lndhub-tg
    restart: always
    stop_grace_period: 10s
    env_file: dynamic_config/lndhub-tg.env
    networks:
      - mongodb
    depends_on:
      - mongodb

  thunderhub:
    container_name: thunderhub
    image: thunderhub:${THUNDERHUB_VERSION}
    build:
      context: src/thunderhub
      args:
        BASE_PATH: ${THUNDERHUB_BASE_PATH}
    restart: always
    stop_grace_period: 10s
    env_file: dynamic_config/thunderhub.env
    networks:
      - lnd
      - nginx
    volumes:
      - ../data/lnd:/lnd:ro
      - ./dynamic_config/thunderhub-accounts.yaml:/var/thunderhub-accounts.yaml
    depends_on:
      - lnd
      - nginx

  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    build: src/nginx
    restart: always
    stop_grace_period: 30s
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
    volumes:
      - ./dynamic_config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../data/certbot/www:/var/www/certbot/:ro
      - ../data/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    container_name: certbot
    image: certbot:${CERTBOT_VERSION}
    build:
      context: src/certbot
      dockerfile: Dockerfile-dev
    restart: always
    stop_grace_period: 1m
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - nginx
    depends_on:
      - nginx
    volumes:
      - ../data/certbot/www/:/var/www/certbot/:rw
      - ../data/certbot/conf/:/etc/letsencrypt/:rw
  
  tor:
    container_name: tor
    image: tor:${TOR_VERSION}
    build: src/tor
    restart: always
    stop_grace_period: 30s
    expose:
      - 9050
      - 9051
    networks:
      - tor
    volumes:
      - ./dynamic_config/torrc:/etc/tor/torrc:ro

  mongodb:
    container_name: mongodb
    image: mongodb:${MONGODB_VERSION}
    build: src/mongodb
    restart: always
    stop_grace_period: 1m
    expose:
      - 27017
    env_file: dynamic_config/mongodb.env
    networks:
      - mongodb
    volumes:
      - ../data/mongodb/:/data/db:rw
      - ./dynamic_config/mongo-auth.js:/docker-entrypoint-initdb.d/mongo-auth.js:ro

networks:
  bitcoind:
    external: false
    name: bitcoind
  lnd:
    external: false
    name: lnd
  lndhub:
    external: false
    name: lndhub
  nginx:
    external: false
    name: nginx
  tor:
    external: false
    name: tor
  mongodb:
    external: false
    name: mongodb